name: Sphinx Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  japanese-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build -t spa-sphinx .
          docker run --rm -v $(pwd):/docs spa-sphinx make html
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: Document
          path: _build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: ${{ github.event_name == 'push' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
