name: Sphinx Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build -t spa-sphinx .
          docker run --rm -v $(pwd):/docs spa-sphinx make html
      - uses: actions/upload-artifact@v1
        with:
          name: document
          path: _build/html
